import type { Dossier } from "./types";

/** Triggers the browser print dialog; `.print-area`/`.no-print` in tokens.css do the layout work. */
export function exportDossierAsPdf(dossier: Dossier): void {
  const originalTitle = document.title;
  const name = [dossier.firm, dossier.partner].filter(Boolean).join(" — ");
  document.title = `PitchGhost — ${name}`;
  window.print();
  window.setTimeout(() => {
    document.title = originalTitle;
  }, 1000);
}

export function dossierToMarkdown(dossier: Dossier): string {
  const lines: string[] = [];
  const heading = [dossier.firm, dossier.partner].filter(Boolean).join(" — ");

  lines.push(`# ${heading}`);
  if (dossier.startup) lines.push(`*Prepared for: ${dossier.startup}*`);
  lines.push("");

  lines.push("## Snapshot");
  lines.push(dossier.snapshot.summary);
  lines.push("");
  lines.push(`- **Stage focus:** ${dossier.snapshot.stageFocus}`);
  lines.push(`- **Check size:** ${dossier.snapshot.checkSize}`);
  lines.push(`- **Sectors:** ${dossier.snapshot.sectors.join(", ")}`);
  lines.push(`- **Geography:** ${dossier.snapshot.geography}`);
  if (dossier.snapshot.fit) {
    lines.push(`- **Fit verdict:** ${dossier.snapshot.fit.label} — ${dossier.snapshot.fit.reasoning}`);
  }
  lines.push("");

  lines.push("## Investment thesis");
  lines.push(dossier.investmentThesis);
  lines.push("");

  lines.push("## Signals they reward");
  dossier.signalsTheyReward.forEach((item) => lines.push(`- ${item}`));
  lines.push("");

  lines.push("## Anti-patterns");
  dossier.antiPatterns.forEach((item) => lines.push(`- ${item}`));
  lines.push("");

  if (dossier.partnerDossier) {
    const pd = dossier.partnerDossier;
    lines.push(`## Partner dossier — ${pd.name}`);
    lines.push(pd.background);
    lines.push("");

    if (pd.notableInvestments.length) {
      lines.push("**Notable investments**");
      pd.notableInvestments.forEach((item) =>
        lines.push(`- ${item.label}${item.source ? ` ([source](${item.source.url}))` : ""}`),
      );
      lines.push("");
    }

    if (pd.publicWriting.length) {
      lines.push("**Public writing**");
      pd.publicWriting.forEach((item) =>
        lines.push(`- ${item.label}${item.source ? ` ([source](${item.source.url}))` : ""}`),
      );
      lines.push("");
    }

    if (pd.statedInterests.length) {
      lines.push("**Stated interests**");
      pd.statedInterests.forEach((item) => lines.push(`- ${item}`));
      lines.push("");
    }

    if (pd.sources.length) {
      lines.push("**Sources**");
      pd.sources.forEach((source) => lines.push(`- [${source.title}](${source.url})`));
      lines.push("");
    }
  }

  if (dossier.recentActivity.length) {
    lines.push("## Recent activity");
    dossier.recentActivity.forEach((item) => {
      lines.push(`### ${item.title}${item.date ? ` (${item.date})` : ""}`);
      lines.push(item.description);
      item.sources.forEach((source) => lines.push(`- [${source.title}](${source.url})`));
      lines.push("");
    });
  }

  lines.push("## Questions to ask in the room");
  dossier.questionsToAsk.forEach((item) => lines.push(`- ${item}`));
  lines.push("");

  lines.push("## Follow-up email draft");
  lines.push(`**Subject:** ${dossier.followUpEmail.subject}`);
  lines.push("");
  lines.push(dossier.followUpEmail.body);
  lines.push("");

  lines.push("---");
  lines.push(
    `Generated by PitchGhost (${dossier.source === "sample" ? "sample dossier" : "live research"}) on ${new Date(dossier.generatedAt).toLocaleDateString()}.`,
  );

  return lines.join("\n");
}

export async function copyDossierAsMarkdown(dossier: Dossier): Promise<boolean> {
  const markdown = dossierToMarkdown(dossier);
  try {
    await navigator.clipboard.writeText(markdown);
    return true;
  } catch {
    return false;
  }
}
